- name: Set variables in environment file.
  become: yes
  become_method: sudo
  lineinfile:
    path: "/etc/environment"
    line: "{{ item.line }}"
  with_items:

#    - { line: "firebase_private_key={{ firebase_private_key }}" }
    - { line: "db_user={{ db_user }}" }
    - { line: "db_password={{ db_password }}" }
    - { line: "db_name={{ db_name }}" }
    - { line: "NODE_ENV=production" }
    - { line: "PGPASSWORD={{ db_password }}"}
    - { line: "jwt_secret={{ jwt_secret }}"}
